name: Tracify CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :99

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup xvfb (Linux)
        if: runner.os == 'Linux'
        run: |
          # Stuff copied wildly from several stackoverflow posts
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 libxcb-shape0 libglib2.0-0 libgl1-mesa-dev
          sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
          # start xvfb in the background
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
      - name: Install Python dependencies
        run: |
          # prerequisites
          python -m pip install --upgrade pip wheel
          python -m pip install coverage flake8 pytest pytest-qt
      - name: Install package
        run: |
          pip install -e .
      - name: List installed packages
        run: |
          pip freeze
      - name: Test with pytest
        run: |
          coverage run --source=mpl_data_cast -m pytest -x tests