name: Tracify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :99

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx libxkbcommon-x11-0 xvfb
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install pytest pytest-mock pytest-qt

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x16 &
          sleep 5
          pgrep Xvfb || { echo "Xvfb failed to start"; exit 1; }

      - name: Verify Xvfb is running
        run: |
          if ! pgrep Xvfb; then
            echo "Xvfb is not running, failing the job.";
            exit 1;
          fi

      - name: Run pytest
        run: python -m pytest tests/ --maxfail=1 --tb=short -v
