name: Tracify CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :99

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx x11-utils libxkbcommon-x11-0 libxi6 libxtst6 libxrender1 libxfixes3 xvfb

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-qt pytest-mock coverage

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          sleep 3

      - name: Debug Xvfb
        run: |
          echo "Checking Xvfb status:"
          pgrep Xvfb
          echo "DISPLAY: $DISPLAY"

      - name: Test
        env:
          QT_DEBUG_PLUGINS: 1
        run: |
          ulimit -c unlimited
          xvfb-run --auto-servernum `which coverage` run -m pytest

      - name: chmod
        if: always()
        run: |
          if [[ -d "$DIRECTORY" ]]; then
            sudo chmod -R +rwx /var/crash
          fi
