name: Tracify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install pytest pytest-mock pytest-qt

      - name: Run Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x16 & # Start Xvfb
          sleep 5 # Give Xvfb time to initialize
          export DISPLAY=:99 # Set DISPLAY variable
          echo "Xvfb started on display $DISPLAY"

          - name: Run tests with pytest
            run: |
              export DISPLAY=:99
              python -m pytest tests/ --maxfail=1